import express from "express";
import isAuth from "../middleware/isAuth.js";
import { createOrder, fetchOrders, fetchRestaurantOrders, fetchSingleOrder, getMyOrders, updateOrderStatus } from "../controller/order.js";
const router = express.Router();
router.get("/customer/my",isAuth,getMyOrders);
router.post("/new",isAuth,createOrder);
router.get("/payment/:id",fetchOrders);
router.get("/:restaurantId",isAuth,fetchRestaurantOrders);
router.put("/:orderId",isAuth,updateOrderStatus);
router.get("/order/:orderId",isAuth,fetchSingleOrder);
export default router;